version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: colife_postgres
    environment:
      POSTGRES_DB: colife_db
      POSTGRES_USER: colife_user
      POSTGRES_PASSWORD: colife_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: